source 'http://rubygems.org'

gem 'rails', '3.0.10'
gem 'heroku'
gem 'haml'
gem 'sass'
gem 'mongo_mapper'
gem 'bson_ext'
gem 'scrapi'
gem 'jammit'
gem 'omniauth'
gem 'omniauth-google-oauth2'
gem 'wikipedia-client'
gem 'wikicloth'
gem 'omniauth-facebook'
gem 'rspec'
gem 'rspec-rails'
gem 'pry'
gem 'pry-debugger'
gem 'capybara', '~> 1.1.2'
gem 'capybara-firebug', '~> 1.2.2'
gem 'capybara-webkit', '~> 0.12.1'
gem 'cucumber'

