          JSCountry.create(:code =>"af", :name =>"Afghanistan")
          JSCountry.create(:code =>"al", :name =>"Albania")
          JSCountry.create(:code =>"dz", :name =>"Algeria")
          JSCountry.create(:code =>"ao", :name =>"Angola")
          JSCountry.create(:code =>"ag", :name =>"Antigua and Barbuda")
          JSCountry.create(:code =>"ar", :name =>"Argentina")
          JSCountry.create(:code =>"am", :name =>"Armenia")
          JSCountry.create(:code =>"au", :name =>"Australia")
          JSCountry.create(:code =>"at", :name =>"Austria")
          JSCountry.create(:code =>"az", :name =>"Azerbaijan")
          JSCountry.create(:code =>"bs", :name =>"Bahamas")
          JSCountry.create(:code =>"bd", :name =>"Bangladesh")
          JSCountry.create(:code =>"bb", :name =>"Barbados")
          JSCountry.create(:code =>"by", :name =>"Belarus")
          JSCountry.create(:code =>"be", :name =>"Belgium")
          JSCountry.create(:code =>"bz", :name =>"Belize")
          JSCountry.create(:code =>"bj", :name =>"Benin")
          JSCountry.create(:code =>"bt", :name =>"Bhutan")
          JSCountry.create(:code =>"bo", :name =>"Bolivia")
          JSCountry.create(:code =>"ba", :name =>"Bosnia and Herzegovina")
          JSCountry.create(:code =>"bw", :name =>"Botswana")
          JSCountry.create(:code =>"br", :name =>"Brazil")
          JSCountry.create(:code =>"bn", :name =>"Brunei Darussalam")
          JSCountry.create(:code =>"bg", :name =>"Bulgaria")
          JSCountry.create(:code =>"bf", :name =>"Burkina Faso")
          JSCountry.create(:code =>"bi", :name =>"Burundi")
          JSCountry.create(:code =>"kh", :name =>"Cambodia")
          JSCountry.create(:code =>"cm", :name =>"Cameroon")
          JSCountry.create(:code =>"ca", :name =>"Canada")
          JSCountry.create(:code =>"cv", :name =>"Cape Verde")
          JSCountry.create(:code =>"cf", :name =>"Central African Republic")
          JSCountry.create(:code =>"td", :name =>"Chad")
          JSCountry.create(:code =>"cl", :name =>"Chile")
          JSCountry.create(:code =>"cn", :name =>"China")
          JSCountry.create(:code =>"co", :name =>"Colombia")
          JSCountry.create(:code =>"km", :name =>"Comoros")
          JSCountry.create(:code =>"cg", :name =>"Congo")
          JSCountry.create(:code =>"cd", :name =>"Congo")
          JSCountry.create(:code =>"cr", :name =>"Costa Rica")
          JSCountry.create(:code =>"ci", :name =>"Cote d'Ivoire")
          JSCountry.create(:code =>"hr", :name =>"Croatia")
          JSCountry.create(:code =>"cu", :name =>"Cuba")
          JSCountry.create(:code =>"cy", :name =>"Cyprus")
          JSCountry.create(:code =>"cz", :name =>"Czech Republic")
          JSCountry.create(:code =>"dk", :name =>"Denmark")
          JSCountry.create(:code =>"dj", :name =>"Djibouti")
          JSCountry.create(:code =>"dm", :name =>"Dominica")
          JSCountry.create(:code =>"do", :name =>"Dominican Republic")
          JSCountry.create(:code =>"ec", :name =>"Ecuador")
          JSCountry.create(:code =>"eg", :name =>"Egypt")
          JSCountry.create(:code =>"sv", :name =>"El Salvador")
          JSCountry.create(:code =>"gq", :name =>"Equatorial Guinea")
          JSCountry.create(:code =>"er", :name =>"Eritrea")
          JSCountry.create(:code =>"ee", :name =>"Estonia")
          JSCountry.create(:code =>"et", :name =>"Ethiopia")
          JSCountry.create(:code =>"fk", :name =>"Falkland Islands")
          JSCountry.create(:code =>"fj", :name =>"Fiji")
          JSCountry.create(:code =>"fi", :name =>"Finland")
          JSCountry.create(:code =>"fr", :name =>"France")
          JSCountry.create(:code =>"gf", :name =>"French Guiana")
          JSCountry.create(:code =>"pf", :name =>"French Polynesia")
          JSCountry.create(:code =>"ga", :name =>"Gabon")
          JSCountry.create(:code =>"gm", :name =>"Gambia")
          JSCountry.create(:code =>"ge", :name =>"Georgia")
          JSCountry.create(:code =>"de", :name =>"Germany")
          JSCountry.create(:code =>"gh", :name =>"Ghana")
          JSCountry.create(:code =>"gr", :name =>"Greece")
          JSCountry.create(:code =>"gl", :name =>"Greenland")
          JSCountry.create(:code =>"gd", :name =>"Grenada")
          JSCountry.create(:code =>"gt", :name =>"Guatemala")
          JSCountry.create(:code =>"gn", :name =>"Guinea")
          JSCountry.create(:code =>"gw", :name =>"Guinea-Bissau")
          JSCountry.create(:code =>"gy", :name =>"Guyana")
          JSCountry.create(:code =>"ht", :name =>"Haiti")
          JSCountry.create(:code =>"hn", :name =>"Honduras")
          JSCountry.create(:code =>"hu", :name =>"Hungary")
          JSCountry.create(:code =>"is", :name =>"Iceland")
          JSCountry.create(:code =>"in", :name =>"India")
          JSCountry.create(:code =>"id", :name =>"Indonesia")
          JSCountry.create(:code =>"ir", :name =>"Iran")
          JSCountry.create(:code =>"iq", :name =>"Iraq")
          JSCountry.create(:code =>"ie", :name =>"Ireland")
          JSCountry.create(:code =>"il", :name =>"Israel")
          JSCountry.create(:code =>"it", :name =>"Italy")
          JSCountry.create(:code =>"jm", :name =>"Jamaica")
          JSCountry.create(:code =>"jp", :name =>"Japan")
          JSCountry.create(:code =>"jo", :name =>"Jordan")
          JSCountry.create(:code =>"kz", :name =>"Kazakhstan")
          JSCountry.create(:code =>"ke", :name =>"Kenya")
          JSCountry.create(:code =>"kw", :name =>"Kuwait")
          JSCountry.create(:code =>"kg", :name =>"Kyrgyz Republic")
          JSCountry.create(:code =>"la", :name =>"Lao People's Democratic Republic")
          JSCountry.create(:code =>"lv", :name =>"Latvia")
          JSCountry.create(:code =>"lb", :name =>"Lebanon")
          JSCountry.create(:code =>"ls", :name =>"Lesotho")
          JSCountry.create(:code =>"lr", :name =>"Liberia")
          JSCountry.create(:code =>"ly", :name =>"Libya")
          JSCountry.create(:code =>"lt", :name =>"Lithuania")
          JSCountry.create(:code =>"mk", :name =>"Macedonia")
          JSCountry.create(:code =>"mg", :name =>"Madagascar")
          JSCountry.create(:code =>"mw", :name =>"Malawi")
          JSCountry.create(:code =>"my", :name =>"Malaysia")
          JSCountry.create(:code =>"mv", :name =>"Maldives")
          JSCountry.create(:code =>"ml", :name =>"Mali")
          JSCountry.create(:code =>"mt", :name =>"Malta")
          JSCountry.create(:code =>"mr", :name =>"Mauritania")
          JSCountry.create(:code =>"mu", :name =>"Mauritius")
          JSCountry.create(:code =>"mx", :name =>"Mexico")
          JSCountry.create(:code =>"md", :name =>"Moldova")
          JSCountry.create(:code =>"mn", :name =>"Mongolia")
          JSCountry.create(:code =>"ma", :name =>"Morocco")
          JSCountry.create(:code =>"mz", :name =>"Mozambique")
          JSCountry.create(:code =>"mm", :name =>"Myanmar")
          JSCountry.create(:code =>"na", :name =>"Namibia")
          JSCountry.create(:code =>"np", :name =>"Nepal")
          JSCountry.create(:code =>"nl", :name =>"Netherlands")
          JSCountry.create(:code =>"nc", :name =>"New Caledonia")
          JSCountry.create(:code =>"nz", :name =>"New Zealand")
          JSCountry.create(:code =>"ni", :name =>"Nicaragua")
          JSCountry.create(:code =>"ne", :name =>"Niger")
          JSCountry.create(:code =>"ng", :name =>"Nigeria")
          JSCountry.create(:code =>"kp", :name =>"North Korea")
          JSCountry.create(:code =>"no", :name =>"Norway")
          JSCountry.create(:code =>"om", :name =>"Oman")
          JSCountry.create(:code =>"pk", :name =>"Pakistan")
          JSCountry.create(:code =>"pa", :name =>"Panama")
          JSCountry.create(:code =>"pg", :name =>"Papua New Guinea")
          JSCountry.create(:code =>"py", :name =>"Paraguay")
          JSCountry.create(:code =>"pe", :name =>"Peru")
          JSCountry.create(:code =>"ph", :name =>"Philippines")
          JSCountry.create(:code =>"pl", :name =>"Poland")
          JSCountry.create(:code =>"pt", :name =>"Portugal")
          JSCountry.create(:code =>"qa", :name =>"Qatar")
          JSCountry.create(:code =>"re", :name =>"Reunion")
          JSCountry.create(:code =>"ro", :name =>"Romania")
          JSCountry.create(:code =>"ru", :name =>"Russian Federation")
          JSCountry.create(:code =>"rw", :name =>"Rwanda")
          JSCountry.create(:code =>"kn", :name =>"Saint Kitts and Nevis")
          JSCountry.create(:code =>"lc", :name =>"Saint Lucia")
          JSCountry.create(:code =>"st", :name =>"Sao Tome and Principe")
          JSCountry.create(:code =>"sa", :name =>"Saudi Arabia")
          JSCountry.create(:code =>"sn", :name =>"Senegal")
          JSCountry.create(:code =>"rs", :name =>"Serbia")
          JSCountry.create(:code =>"sc", :name =>"Seychelles")
          JSCountry.create(:code =>"sl", :name =>"Sierra Leone")
          JSCountry.create(:code =>"sg", :name =>"Singapore")
          JSCountry.create(:code =>"sk", :name =>"Slovakia")
          JSCountry.create(:code =>"si", :name =>"Slovenia")
          JSCountry.create(:code =>"sb", :name =>"Solomon Islands")
          JSCountry.create(:code =>"so", :name =>"Somalia")
          JSCountry.create(:code =>"za", :name =>"South Africa")
          JSCountry.create(:code =>"kr", :name =>"South Korea")
          JSCountry.create(:code =>"es", :name =>"Spain")
          JSCountry.create(:code =>"lk", :name =>"Sri Lanka")
          JSCountry.create(:code =>"sd", :name =>"Sudan")
          JSCountry.create(:code =>"sr", :name =>"Suriname")
          JSCountry.create(:code =>"sz", :name =>"Swaziland")
          JSCountry.create(:code =>"se", :name =>"Sweden")
          JSCountry.create(:code =>"ch", :name =>"Switzerland")
          JSCountry.create(:code =>"sy", :name =>"Syrian Arab Republic")
          JSCountry.create(:code =>"tw", :name =>"Taiwan")
          JSCountry.create(:code =>"tj", :name =>"Tajikistan")
          JSCountry.create(:code =>"tz", :name =>"Tanzania")
          JSCountry.create(:code =>"th", :name =>"Thailand")
          JSCountry.create(:code =>"tl", :name =>"Timor-Leste")
          JSCountry.create(:code =>"tg", :name =>"Togo")
          JSCountry.create(:code =>"tt", :name =>"Trinidad and Tobago")
          JSCountry.create(:code =>"tn", :name =>"Tunisia")
          JSCountry.create(:code =>"tr", :name =>"Turkey")
          JSCountry.create(:code =>"tm", :name =>"Turkmenistan")
          JSCountry.create(:code =>"ug", :name =>"Uganda")
          JSCountry.create(:code =>"ua", :name =>"Ukraine")
          JSCountry.create(:code =>"ae", :name =>"United Arab Emirates")
          JSCountry.create(:code =>"gb", :name =>"United Kingdom")
          JSCountry.create(:code =>"us", :name =>"United States of America")
          JSCountry.create(:code =>"uy", :name =>"Uruguay")
          JSCountry.create(:code =>"uz", :name =>"Uzbekistan")
          JSCountry.create(:code =>"vu", :name =>"Vanuatu")
          JSCountry.create(:code =>"ve", :name =>"Venezuela")
          JSCountry.create(:code =>"vn", :name =>"Vietnam")
          JSCountry.create(:code =>"ye", :name =>"Yemen")
          JSCountry.create(:code =>"zm", :name =>"Zambia")
          JSCountry.create(:code =>"zw", :name =>"Zimbabwe")
