module VisaStatuses
  VISA_NOT_REQUIRED = 0
  VISA_AVAILABLE_ON_ARRIVAL = 1
  ONLINE_FORM_REQUIRED_PRIOR_TO_ARRIVAL = 2
  VISA_REQUIRED_PRIOR_TO_ARRIVAL = 3
  TRAVEL_HIGHLY_RESTRICTED_OR_FORBIDDEN = 4
  COUNTRY_OF_CITIZENSHIP = 5
  DATA_UNCLEAR = 6
end
